name: 'Issue Code Generator'
description: 'Generates code solutions for GitHub issues using Aider'
inputs:
  openai-api-key:
    description: 'OpenAI API key for Aider'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Prepare Issue Content
      uses: actions/github-script@v7
      with:
        script: |
          const { prepareIssueFile } = require('./.github/scripts/prepare-issue.js');
          await prepareIssueFile(context.payload.issue);
    
    - name: Generate Solution with Aider
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/repo \
          -e OPENAI_API_KEY=${{ inputs.openai-api-key }} \
          paulgauthier/aider:latest \
          --no-git \
          --model gpt-4-1106-preview \
          --input-issue-file /repo/.github/temp/issue.md \
          /repo
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      shell: bash
      run: npm ci
      
    - name: Process Changes and Create PR
      uses: actions/github-script@v7
      with:
        script: |
          const { processAiderChanges } = require('./.github/scripts/process-changes.js');
          await processAiderChanges({ github, context, exec });