name: Issue Code Generator

on:
  workflow_call:
    inputs:
      prompt:
        description: "Prompt for the code generation"
        required: true
        type: string
      pr_title:
        description: "Title for the pull request"
        required: true
        type: string
      branch_name:
        description: "Branch name to checkout"
        required: true
        type: string
      github_token:
        description: "GitHub Token"
        required: true
        type: string
      openai_api_key:
        description: "OpenAI API Key"
        required: true
        type: string

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Checkout New Branch
        run: git checkout -b ${{ github.event.inputs.branch_name }}

      - name: Run Aider Docker Command
        run: docker run -rm --user $(id -u):$(id -g) --volume $(pwd):/app paulgauthier/aider --openai-api-key ${{ github.event.inputs.openai_api_key }} --message "${{ github.event.inputs.prompt }}" --yes-always --no-show-release-notes

      - name: Push Changes
        run: git push

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          gh pr create --title "${{ github.event.inputs.pr_title }}" --body "Code generated from prompt:\n${{ github.event.inputs.prompt }}" --base main --head ${{ github.event.inputs.branch_name }}

