name: Issue Code Generator

on:
  issues:
    types: [opened, edited]

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Code Solution
        uses: ./ # Uses the local action
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}