name: Issue Code Generator

on:
  issues:
    types: [opened, edited]

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Run Aider Docker Command
        run: docker run -rm --user $(id -u):$(id -g) --volume $(pwd):/app paulgauthier/aider --openai-api-key $OPENAI_API_KEY --message "/code $@" --yes-always --no-show-release-notes

