name: Issue Code Generator

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt for the code generation'
        required: true
      openai_api_key:
        description: 'OpenAI API Key'
        required: true

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Run Aider Docker Command
        run: docker run -rm --user $(id -u):$(id -g) --volume $(pwd):/app paulgauthier/aider --openai-api-key ${{ github.event.inputs.openai_api_key }} --message "${{ github.event.inputs.prompt }}" --yes-always --no-show-release-notes

