name: Issue Code Generator

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt for the code generation'
        required: true
      branch_name:
        description: 'Branch name to checkout'
        required: true
      openai_api_key:
        description: 'OpenAI API Key'
        required: true

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Checkout New Branch
        run: git checkout -b ${{ github.event.inputs.branch_name }}

      - name: Run Aider Docker Command
        run: docker run -rm --user $(id -u):$(id -g) --volume $(pwd):/app paulgauthier/aider --openai-api-key ${{ github.event.inputs.openai_api_key }} --message "${{ github.event.inputs.prompt }}" --yes-always --no-show-release-notes

      - name: Commit and Push Changes
        run: node .github/scripts/utils/git.js commitAndPush ${{ github.event.inputs.branch_name }} "Automated code changes"

      - name: Create Pull Request
        run: node .github/scripts/utils/github.js createPullRequest ${{ github.repository_owner }} ${{ github.event.inputs.branch_name }} "${{ github.event.inputs.branch_name }}" "${{ github.event.inputs.prompt }}"

