name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      prompt: # "Prompt for the code generation"
        required: true
        type: string
      pr_title: # "Title for the pull request"
        required: true
        type: string
      branch_name: # "Branch name to checkout"
        required: true
        type: string

jobs:
  trigger-code-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Issue Code Generator
        uses: ./.github/actions/issue-code-generator
        with:
          prompt: ${{ inputs.prompt }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          pr_title: ${{ inputs.pr_title }}
          branch_name: ${{ inputs.branch_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

