name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      prompt: # "Prompt for the code generation"
        required: true
        default: "Create a new shell script file that prints 'Hello, World!'"
        type: string
      pr_title: # "Title for the pull request"
        required: true
        default: "Hello world"
        type: string
      branch_name: # "Branch name to checkout"
        required: true
        default: "hello-world"
        type: string

jobs:
  trigger-code-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Issue Code Generator
        uses: ./.github/actions/issue-code-generator
        with:
          prompt: ${{ inputs.prompt }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          pr_title: ${{ inputs.pr_title }}
          branch_name: ${{ inputs.branch_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Checkout New Branch
      #   run: git checkout -b ${{ inputs.branch_name }}

      # - name: Run Aider Docker Command
      #   run: docker run --rm --user $(id -u):$(id -g) --volume $(pwd):/app paulgauthier/aider --openai-api-key ${{ secrets.OPENAI_API_KEY }} --message "${{ inputs.prompt }}" --yes-always --no-show-release-notes

      # - name: Set Upstream Branch
      #   run: git push --set-upstream origin ${{ inputs.branch_name }}

      # - name: Push Changes
      #   run: git push

      # - name: Create Pull Request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "GitHub Actions Bot"
      #     gh pr create --title "${{ inputs.pr_title }}" --body "Code generated from prompt:\n${{ inputs.prompt }}" --base main --head ${{ inputs.branch_name }}

